// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD85Sqq4uDFqGJOXAvNEMTW1UiTguOneqo',
    appId: '1:814035918281:web:675dc7ae75af57b8bd5c18',
    messagingSenderId: '814035918281',
    projectId: 'to-do-app-firebase-b3d75',
    authDomain: 'to-do-app-firebase-b3d75.firebaseapp.com',
    storageBucket: 'to-do-app-firebase-b3d75.appspot.com',
    measurementId: 'G-ZLWWSL0ZQ2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ggf1msl3M9iqJDCEux0IYdGLIcge7WQ',
    appId: '1:814035918281:ios:31058e65f68ff879bd5c18',
    messagingSenderId: '814035918281',
    projectId: 'to-do-app-firebase-b3d75',
    storageBucket: 'to-do-app-firebase-b3d75.appspot.com',
    iosBundleId: 'com.example.toDoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ggf1msl3M9iqJDCEux0IYdGLIcge7WQ',
    appId: '1:814035918281:ios:31058e65f68ff879bd5c18',
    messagingSenderId: '814035918281',
    projectId: 'to-do-app-firebase-b3d75',
    storageBucket: 'to-do-app-firebase-b3d75.appspot.com',
    iosBundleId: 'com.example.toDoAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85Sqq4uDFqGJOXAvNEMTW1UiTguOneqo',
    appId: '1:814035918281:web:8dea0faaac629d38bd5c18',
    messagingSenderId: '814035918281',
    projectId: 'to-do-app-firebase-b3d75',
    authDomain: 'to-do-app-firebase-b3d75.firebaseapp.com',
    storageBucket: 'to-do-app-firebase-b3d75.appspot.com',
    measurementId: 'G-YGDTQ47403',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKER4ECTTbm69iaB2w6SHZXGPUuDrc10',
    appId: '1:814035918281:android:13b969c4f6d359cabd5c18',
    messagingSenderId: '814035918281',
    projectId: 'to-do-app-firebase-b3d75',
    storageBucket: 'to-do-app-firebase-b3d75.appspot.com',
  );
}
