// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQq6Y5CPdcl9xoDD5SnaniXAu4xf7eYC4',
    appId: '1:1077973939949:web:e605daf00c6577f1bdfee4',
    messagingSenderId: '1077973939949',
    projectId: 'my-app-ef670',
    authDomain: 'my-app-ef670.firebaseapp.com',
    storageBucket: 'my-app-ef670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOd6erUEtbLUgvn8SPAAX2HpfW0yc8WA',
    appId: '1:1077973939949:ios:2c7881d3e1ce8c21bdfee4',
    messagingSenderId: '1077973939949',
    projectId: 'my-app-ef670',
    storageBucket: 'my-app-ef670.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOd6erUEtbLUgvn8SPAAX2HpfW0yc8WA',
    appId: '1:1077973939949:ios:2c7881d3e1ce8c21bdfee4',
    messagingSenderId: '1077973939949',
    projectId: 'my-app-ef670',
    storageBucket: 'my-app-ef670.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQq6Y5CPdcl9xoDD5SnaniXAu4xf7eYC4',
    appId: '1:1077973939949:web:6ff2d84151ecc044bdfee4',
    messagingSenderId: '1077973939949',
    projectId: 'my-app-ef670',
    authDomain: 'my-app-ef670.firebaseapp.com',
    storageBucket: 'my-app-ef670.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtReKn7IM48gEv6Bqcfn65wsh0n3SInoE',
    appId: '1:1077973939949:android:d1f47163d4a0cbf0bdfee4',
    messagingSenderId: '1077973939949',
    projectId: 'my-app-ef670',
    storageBucket: 'my-app-ef670.appspot.com',
  );

}